### ISSUE TITLE
Unexpected token - Gulp 

### ISSUE THREAD

**Issue by Thiruppathi** [GoogleChrome/ioweb2016#1014]
Getting the following error, when tried to build using `gulp` command.

`
$ gulp
/Users/thiru/apps/ioweb2016/gulpfile.js:179
  ].map(script => `${IOWA.appDir}/${script}`);
               ^^

SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:411:25)
    at Object.Module._extensions..js (module.js:446:10)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Liftoff.handleArguments (/Users/thiru/.nvm/versions/io.js/v1.8.1/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/Users/thiru/.nvm/versions/io.js/v1.8.1/lib/node_modules/gulp/node_modules/liftoff/index.js:193:16)
    at module.exports (/Users/thiru/.nvm/versions/io.js/v1.8.1/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
`

**Comment by Thiruppathi** [comment]
Sorry. I was using wrong version of node. Able to pass through this error after using 
`nvm use 5.0`.

Hence closing this issue.
