### ISSUE TITLE
fsevents@1.0.14 dependency incompatible with Linux

### ISSUE THREAD

**Issue by dman777** [GoogleChrome/ioweb2016#1023]
When doing a clone and npm install, I get:

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm ERR! Linux 4.1.15-gentoo-r1
npm ERR! argv "/home/one/.nvm/versions/node/v4.2.2/bin/node" "/home/one/.nvm/versions/node/v4.2.2/bin/npm" "install"
npm ERR! node v4.2.2
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! GoogleIOWeb@ postinstall: `gulp setup`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the GoogleIOWeb@ postinstall script 'gulp setup'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the GoogleIOWeb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp setup
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs GoogleIOWeb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls GoogleIOWeb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/one/github/ioweb2016/npm-debug.log
```

I assume this would be because it was developed on Mac OS. But I am curious how it was overcomed for production since, I assume, google app engine would be using Linux. 

Or is this because I do not have `Go` language installed? What I would like to do is run this strictly for WCT testing, which I hope would be independent of the backend. 

```
one@development ~/github/ioweb2016 $ gulp setup
[02:35:59] Using gulpfile ~/github/ioweb2016/gulpfile.js
[02:35:59] Starting 'setup'...
[02:35:59] Starting 'bower'...
[02:35:59] Starting 'godeps'...
[02:35:59] Starting 'addgithooks'...
[02:35:59] Finished 'addgithooks' after 49 ms
package github.com/google/http2preload: cannot download, $GOPATH not set. For more details see: go help gopath
package github.com/googlechrome/push-encryption-go/webpush: cannot download, $GOPATH not set. For more details see: go help gopath
package golang.org/x/net/context: cannot download, $GOPATH not set. For more details see: go help gopath
package golang.org/x/oauth2: cannot download, $GOPATH not set. For more details see: go help gopath
package golang.org/x/oauth2/jwt: cannot download, $GOPATH not set. For more details see: go help gopath
package google.golang.org/appengine: cannot download, $GOPATH not set. For more details see: go help gopath
package google.golang.org/appengine/datastore: cannot download, $GOPATH not set. For more details see: go help gopath
package google.golang.org/appengine/log: cannot download, $GOPATH not set. For more details see: go help gopath
package google.golang.org/appengine/memcache: cannot download, $GOPATH not set. For more details see: go help gopath
package google.golang.org/appengine/taskqueue: cannot download, $GOPATH not set. For more details see: go help gopath
package google.golang.org/appengine/urlfetch: cannot download, $GOPATH not set. For more details see: go help gopath
package google.golang.org/appengine/user: cannot download, $GOPATH not set. For more details see: go help gopath
[02:36:00] 'godeps' errored after 1.01 s
[02:36:00] Error: 1
    at formatError (/usr/lib64/node_modules/gulp-cli/lib/versioned/^3.7.0/formatError.js:20:10)
    at Gulp.<anonymous> (/usr/lib64/node_modules/gulp-cli/lib/versioned/^3.7.0/log/events.js:41:15)
    at emitOne (events.js:82:20)
    at Gulp.emit (events.js:169:7)
    at Gulp.Orchestrator._emitTaskDone (/home/one/github/ioweb2016/node_modules/orchestrator/index.js:264:8)
    at /home/one/github/ioweb2016/node_modules/orchestrator/index.js:275:23
    at finish (/home/one/github/ioweb2016/node_modules/orchestrator/lib/runTask.js:21:8)
    at ChildProcess.cb (/home/one/github/ioweb2016/node_modules/orchestrator/lib/runTask.js:29:3)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
[02:36:00] 'setup' errored after 1.02 s
[02:36:00] Error in plugin 'run-sequence(godeps)'
Error
    at finish (/home/one/github/ioweb2016/node_modules/run-sequence/index.js:56:13)
    at Gulp.onError (/home/one/github/ioweb2016/node_modules/run-sequence/index.js:67:4)
    at emitOne (events.js:82:20)
    at Gulp.emit (events.js:169:7)
    at Gulp.Orchestrator._emitTaskDone (/home/one/github/ioweb2016/node_modules/orchestrator/index.js:264:8)
    at /home/one/github/ioweb2016/node_modules/orchestrator/index.js:275:23
    at finish (/home/one/github/ioweb2016/node_modules/orchestrator/lib/runTask.js:21:8)
    at ChildProcess.cb (/home/one/github/ioweb2016/node_modules/orchestrator/lib/runTask.js:29:3)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
bower invalid-meta  The "name" is recommended to be lowercase, can contain digits, dots, dashes
[02:36:01] Finished 'bower' after 1.62 s
one@development ~/github/ioweb2016 $ 
```

**Comment by ebidel** [comment]
`gulp` is ran locally for build time stuff. In production, GAE doesn't use it.

As mentioned before, we didn't use wct in 2016 but there are left over relics from the previous year. I would check out https://github.com/Polymer/web-component-tester for examples and good docs on how to get started. Or check out Polymer's elements to see examples of test/ directories.
