### ISSUE TITLE
Npm install wont work

### ISSUE THREAD

**Issue by GiacomoSilli** [GoogleChrome/ioweb2016#1024]
Hello, i'm unable to use this iosweb2016
Thats the problem:

```
ioweb2016>npm install

> GoogleIOWeb@ postinstall C:\Users\****\Documenti\ioweb2016
> gulp setup

[12:57:10] Using gulpfile ~\Documenti\ioweb2016\gulpfile.js
[12:57:10] Starting 'setup'...
[12:57:10] Starting 'bower'...
[12:57:10] Starting 'godeps'...
[12:57:10] Starting 'addgithooks'...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn ../node_modules/bower/bin/bower ENOENT
    at exports._errnoException (util.js:907:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:974:3

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.15
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\****\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.7
npm ERR! code ELIFECYCLE
npm ERR! GoogleIOWeb@ postinstall: `gulp setup`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the GoogleIOWeb@ postinstall script 'gulp setup'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the GoogleIOWeb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp setup
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs GoogleIOWeb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls GoogleIOWeb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
```

**Comment by psnmissaka** [comment]
i have the same issue. Did anyone worked that out?

**Comment by krsnadjava25** [comment]
I got the same issue here. It fails on `gulp setup`
